# Generated by Django 5.0.3 on 2024-03-15 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikelanlage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artikel',
            options={'verbose_name': 'Artikel', 'verbose_name_plural': 'Artikel'},
        ),
        migrations.AlterModelOptions(
            name='lieferant',
            options={'verbose_name': 'Lieferant', 'verbose_name_plural': 'Lieferanten'},
        ),
        migrations.AlterField(
            model_name='artikel',
            name='anforderer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='konto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artikelanlage.konto'),
        ),
        migrations.AlterField(
            model_name='konto',
            name='bezeichnung',
            field=models.CharField(max_length=40, verbose_name='Konto Bezeichnung'),
        ),
        migrations.AlterField(
            model_name='konto',
            name='nummer',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
