# Generated by Django 5.0.3 on 2024-03-14 12:43

import django.core.validators
import django.db.models.deletion
import events.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Kategorie', 'verbose_name_plural': 'Kategorien'},
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.category', verbose_name='Kategorie'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(validators=[events.validators.datetime_in_future]),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(help_text='Beschreibung des Events', validators=[events.validators.BadWordFilter(evil_word_list=['evil', 'doof'])], verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3, message='Name ist kurz!')]),
        ),
        migrations.AlterField(
            model_name='event',
            name='sub_title',
            field=models.CharField(blank=True, help_text='Wenn Kategorie science, darf hier nicht science stehen', max_length=200, null=True),
        ),
    ]
